version: 0.0.1
node:
  hostIP: 0.0.0.0
  port: 8018
  registerToken: ""
  healthInterval: 30s
server:
  host: 0.0.0.0:8801
  timeout: 60s
docker:
  host: unix:///var/run/docker.sock
  rootDir: /var/lib/docker
  apiVersion: ""
  timeout: 60s